2023-05-22 00:24:32,090 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 194747ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 00:31:20,363 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 408269ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 00:41:28,222 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 607857ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 00:58:39,958 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1031731ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 01:15:55,850 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1035889ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 01:33:01,402 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1025550ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 01:48:54,336 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 952931ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 02:04:59,324 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 964987ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 02:20:49,422 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 950097ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 02:38:13,284 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1005271ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 02:54:20,269 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 966983ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 03:10:49,242 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 988972ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 03:28:06,211 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1036966ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 03:46:03,200 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1076986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 04:02:42,198 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 998996ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 04:20:38,187 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1075986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 04:37:14,186 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 995995ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 04:53:17,178 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 962991ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 05:08:47,157 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 929977ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 05:24:19,593 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 932431ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 05:42:13,454 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1073858ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 05:59:43,353 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1049896ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 06:16:13,263 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 989904ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 06:31:48,194 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 934931ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 06:46:56,097 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 907901ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 07:03:11,028 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 974929ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 07:18:26,021 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 914991ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 07:35:18,019 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1011995ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 07:50:56,006 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 937986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 08:00:24,990 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 568981ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 08:16:29,978 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 964984ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 08:34:25,963 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1075982ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 08:50:55,939 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 989975ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 09:08:27,918 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1051978ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 09:23:56,904 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 928983ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 09:40:09,884 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 972978ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 09:58:14,428 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1084542ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 10:15:54,362 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1059930ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 10:33:11,198 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1036831ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 11:06:18,051 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1012908ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 11:22:40,997 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 982914ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 11:39:32,869 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1011868ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 11:55:21,800 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 948927ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 12:01:44,716 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 382914ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 12:08:39,339 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 194624ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 12:26:07,766 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1048421ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 12:43:56,837 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1069062ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 13:01:00,810 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1023971ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 13:21:19,939 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 995753ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 13:53:02,941 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 971934ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 14:08:21,913 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 918967ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 14:26:14,425 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 284273ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 16:13:25,848 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 831145ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 16:29:43,849 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 937984ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 18:09:49,063 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 998161ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 18:27:35,468 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1026393ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 19:03:51,942 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 976215ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 19:22:04,454 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1052499ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 19:44:04,385 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 419847ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 20:02:03,795 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1039411ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 20:18:28,402 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 944595ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 20:49:43,335 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 974885ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 21:23:00,020 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 945409ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 22:38:56,823 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 528335ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 23:25:05,229 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 916571ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-22 23:57:10,767 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1025422ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

